coverage:
  precision: 2
  round: down
  range: 70..100
  status:
    project:
      default:
        threshold: 1% # the leniency in hitting the target
ignore:
  - 'src/reactTestUtils.tsx'
  - 'src/apollo'
  - 'src/reportWebVitals.ts'
  - 'src/setupTests.js'
